INSERT INTO users (username, password, role) VALUES ('admin', 'admin123', 'ADMIN');
INSERT INTO users (username, password, role) VALUES ('user1', 'password1', 'USER');
INSERT INTO users (username, password, role) VALUES ('user2', 'password2', 'USER');
INSERT INTO users (username, password, role) VALUES ('user3', 'password3', 'USER');
INSERT INTO users (username, password, role) VALUES ('user4', 'password4', 'USER');
INSERT INTO users (username, password, role) VALUES ('user5', 'password5', 'USER');
INSERT INTO users (username, password, role) VALUES ('user6', 'password6', 'USER');
INSERT INTO users (username, password, role) VALUES ('user7', 'password7', 'USER');
INSERT INTO users (username, password, role) VALUES ('user8', 'password8', 'USER');
INSERT INTO users (username, password, role) VALUES ('user9', 'password9', 'USER');
INSERT INTO users (username, password, role) VALUES ('user10', 'password10', 'USER');
INSERT INTO users (username, password, role) VALUES ('user11', 'password11', 'USER');
INSERT INTO users (username, password, role) VALUES ('user12', 'password12', 'USER');
INSERT INTO users (username, password, role) VALUES ('user13', 'password13', 'USER');
INSERT INTO users (username, password, role) VALUES ('user14', 'password14', 'USER');
INSERT INTO users (username, password, role) VALUES ('user15', 'password15', 'USER');
INSERT INTO users (username, password, role) VALUES ('user16', 'password16', 'USER');
INSERT INTO users (username, password, role) VALUES ('user17', 'password17', 'USER');
INSERT INTO users (username, password, role) VALUES ('user18', 'password18', 'USER');
INSERT INTO users (username, password, role) VALUES ('user19', 'password19', 'USER');
INSERT INTO users (username, password, role) VALUES ('user20', 'password20', 'USER');
INSERT INTO users (username, password, role) VALUES ('user21', 'password21', 'USER');
INSERT INTO users (username, password, role) VALUES ('user22', 'password22', 'USER');
INSERT INTO users (username, password, role) VALUES ('user23', 'password23', 'USER');
INSERT INTO users (username, password, role) VALUES ('user24', 'password24', 'USER');
INSERT INTO users (username, password, role) VALUES ('user25', 'password25', 'USER');
INSERT INTO users (username, password, role) VALUES ('user26', 'password26', 'USER');
INSERT INTO users (username, password, role) VALUES ('user27', 'password27', 'USER');
INSERT INTO users (username, password, role) VALUES ('user28', 'password28', 'USER');
INSERT INTO users (username, password, role) VALUES ('user29', 'password29', 'USER');
INSERT INTO users (username, password, role) VALUES ('user30', 'password30', 'USER');

INSERT INTO books (title, author, available_copies) VALUES ('The Great Gatsby', 'F. Scott Fitzgerald', 5);
INSERT INTO books (title, author, available_copies) VALUES ('1984', 'George Orwell', 7);
INSERT INTO books (title, author, available_copies) VALUES ('To Kill a Mockingbird', 'Harper Lee', 4);
INSERT INTO books (title, author, available_copies) VALUES ('The Catcher in the Rye', 'J.D. Salinger', 6);
INSERT INTO books (title, author, available_copies) VALUES ('Pride and Prejudice', 'Jane Austen', 3);
INSERT INTO books (title, author, available_copies) VALUES ('The Hobbit', 'J.R.R. Tolkien', 8);
INSERT INTO books (title, author, available_copies) VALUES ('Moby Dick', 'Herman Melville', 2);
INSERT INTO books (title, author, available_copies) VALUES ('War and Peace', 'Leo Tolstoy', 4);
INSERT INTO books (title, author, available_copies) VALUES ('The Odyssey', 'Homer', 5);
INSERT INTO books (title, author, available_copies) VALUES ('Crime and Punishment', 'Fyodor Dostoevsky', 3);



INSERT INTO borrowed_books (user_id, book_id) VALUES (2, 1);
INSERT INTO borrowed_books (user_id, book_id) VALUES (3, 1);
INSERT INTO borrowed_books (user_id, book_id) VALUES (4, 2);
INSERT INTO borrowed_books (user_id, book_id) VALUES (5, 3);
INSERT INTO borrowed_books (user_id, book_id) VALUES (6, 4);
INSERT INTO borrowed_books (user_id, book_id) VALUES (7, 5);
INSERT INTO borrowed_books (user_id, book_id) VALUES (8, 6);
INSERT INTO borrowed_books (user_id, book_id) VALUES (9, 7);
INSERT INTO borrowed_books (user_id, book_id) VALUES (10, 8);
INSERT INTO borrowed_books (user_id, book_id) VALUES (11, 9);
INSERT INTO borrowed_books (user_id, book_id) VALUES (12, 10);
INSERT INTO borrowed_books (user_id, book_id) VALUES (13, 2);
INSERT INTO borrowed_books (user_id, book_id) VALUES (14, 4);
INSERT INTO borrowed_books (user_id, book_id) VALUES (15, 6);
INSERT INTO borrowed_books (user_id, book_id) VALUES (16, 8);
INSERT INTO borrowed_books (user_id, book_id) VALUES (17, 9);
INSERT INTO borrowed_books (user_id, book_id) VALUES (18, 10);
INSERT INTO borrowed_books (user_id, book_id) VALUES (19, 1);
INSERT INTO borrowed_books (user_id, book_id) VALUES (20, 3);
